version: '3.8'

services:
  app:
    build: . # Construye la imagen usando el Dockerfile en el directorio actual
    container_name: api-eventos-app
    ports:
      - "8080:8080" # Mapea el puerto 8080 del host al 8080 del contenedor
    environment: # Variables de entorno leídas del .env
      SPRING_DATASOURCE_URL: ${NEON_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${NEON_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${NEON_DB_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

      SPRING_ACTIVE_PROFILE: dev
    # No necesitamos "depends_on" ni servicio "db" porque Neon.tech es externo