#spring.datasource.url=jdbc:h2:mem:gestion_eventos_db
#spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1M;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.url=${NEON_DB_URL}
spring.datasource.username=${NEON_DB_USERNAME}
spring.datasource.password=${NEON_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
# Update no se recomienda en produccion, solamente en desarrollo. Ya que puede fallar.

# Create borra todas las tablas que correspondan a nuestras entidades y luego vuelve a crearlas desde 0. Es util para ejecutar pruebas
# con la base de datos limpia desde 0.

# Validate no crea, actualiza o borra nada. Solo valida que las tablas y las columnas de la base de datos coincidan exactamente con las
# clases Entity; si no, la aplicacion falla. Se usa en produccion.

# Tambien se usa none, no hace nada. Se suele usar en produccion. Es la mas segura y recomendada para produccion. Asume que la base
# ya esta validada por herramientas externas. Es la mas usada.
spring.jpa.show-sql=true
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


jwt.secret=${JWT_SECRET}

jwt.expiration=${JWT_EXPIRATION}
# expira en 10 mins.


# JPA - Api de Persistencia de Java. No es un programa ni libreria, si no que es un conjunto de especificaciones de Java como lo
# pueden ser interfaces, anotaciones, que definen un estandar de como mapear clases de Java a tablas de bases de datos SQL.

# Hibernate es la implementacion mas popular y robusta de la especificacion JPA. Lee nuestras anotaciones JPA, entiende la estructura de
# nuestros objetos y se encarga de generar y ejecutar nuestras sentencias SQL que son las DML y DDL.

# DDL - Lenguaje de Definicion de Datos (CREATE TABLE, ALTER TABLE, DROP TABLE). Lo que tiene que ver con la definicion de datos.

# DML - Lenguaje de Manipulacion de Datos (SELECT, INSERT, UPDATE, DELETE).


#logging.level.root=INFO
#logging.level.com.juliandonati.api=DEBUG
#logging.level.org.springframework=DEBUG
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan(%logger{36}) - %msg%n
